### ISSUE TITLE
关于hitTest

### ISSUE THREAD

**Issue by MuRanJiangXia** [lyb5834/YBAttributeTextTapForSwfit#8]
override open func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
这个方法一直在调用，而且isTapAction这个属性一旦置为true 就不会再置为false了，
我出现了了几次问题，在tableveiw中使用这个，会闪退

**Comment by MuRanJiangXia** [comment]
override open func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        if isTapAction == true {
            
            let result = yb_getTapFrame(point, result: { (
                String, NSRange, Int) -> Void in
                
            })
            
            if result == true {
                return self
            }
            return super.hitTest(point, with: event)
        }
        return super.hitTest(point, with: event)
    }
应该这样处理一下吧，又没其他的好方法么？只要设置isTapAction = true ,所有的 点击事件都会走这个方法

**Comment by lyb5834** [comment]
你好，swift 版本有很多bug，推荐使用oc版本，待oc版本稳定了，我会更新swift版本的

**Comment by MuRanJiangXia** [comment]
好的好的，
